//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboPiedade
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        public int IdHorario { get; set; }
        public int IdBairro { get; set; }
        public Nullable<byte> TipoSaida { get; set; }
        public Nullable<byte> TipoDia { get; set; }
        public string Hora { get; set; }
    
        public virtual Bairros Bairros { get; set; }
    }
}
