//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboPiedade
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UrBUSEntities : DbContext
    {
        public UrBUSEntities()
            : base("name=UrBUSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bairros> Bairros { get; set; }
        public virtual DbSet<Horarios> Horarios { get; set; }
        public virtual DbSet<Itinerarios> Itinerarios { get; set; }
        public virtual DbSet<Mapas> Mapas { get; set; }
        public virtual DbSet<Observacoes> Observacoes { get; set; }
    }
}
